/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every dataset, with its counts
         * @description List the catalog.
         */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One dataset, with its channels and capture groups
         * @description Everything the browser needs to build its filters.
         */
        get: operations["get_dataset_api_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a dataset and its rows
         * @description Remove the catalog entry. **Source images are never touched** (ADR-0001).
         *
         *     Refused while an experiment references the dataset: an experiment freezes its
         *     configuration at creation, so orphaning one would leave results that cannot be
         *     explained (ADR-0005).
         */
        delete: operations["delete_dataset_api_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of samples, filtered
         * @description Page through a dataset's samples in a stable order.
         *
         *     Ordered by capture group then by natural numeric identity, so `10` follows `9` rather
         *     than `1`, and so a scroll position still means the same thing after a re-import has
         *     inserted rows in the middle.
         */
        get: operations["list_samples_api_datasets__dataset_id__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label many samples at once
         * @description Label a selection, or everything matching a filter, in one request.
         *
         *     Labelling one sample at a time is fine for correcting a handful and hopeless for a
         *     directory that is entirely one class — which is the common case on import, and the
         *     reason this exists. Like the single-sample route it marks every row it touches
         *     `manual`, so a re-import of the same tree cannot undo the work (ADR-0013).
         *
         *     The filter form is resolved server-side from the grid's own `_where` clause, so the
         *     set that gets labelled is provably the set whose count the UI displayed.
         */
        patch: operations["update_labels_api_datasets__dataset_id__samples_patch"];
        trace?: never;
    };
    "/api/datasets/{dataset_id}/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One sample and all of its images
         * @description One grouped sample. Its channel tabs are built from this list, whatever its length.
         */
        get: operations["get_sample_api_datasets__dataset_id__samples__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set a sample's label
         * @description Record an operator's label.
         *
         *     Marks the sample `manual`, which is what makes the correction survive the next import
         *     of the same tree (ADR-0013).
         */
        patch: operations["update_label_api_datasets__dataset_id__samples__sample_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backend liveness, version and database state
         * @description Report the backend's version, its schema version, and where its data lives.
         */
        get: operations["read_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/prewarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a dataset's cached tiers up front
         * @description Start a pre-warm job so the first browse of a dataset is not the slowest one.
         */
        post: operations["start_prewarm_api_images_prewarm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/{tier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One rendered tier of an image
         * @description Serve `thumb`, `preview` or `full`.
         *
         *     `thumb` and `preview` are rendered once and cached; `full` is rendered per request,
         *     because caching a lossless copy of every image would cost most of a gigabyte per
         *     dataset to avoid re-rendering something that is looked at once.
         */
        get: operations["read_tier_api_images__image_id___tier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Import adapters and their option schemas
         * @description List the registered adapters. Their JSON Schemas drive the import form.
         */
        get: operations["list_adapters_api_import_adapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan a directory into a reviewable manifest
         * @description Start a scan job. Nothing is written to the catalog by this or by the job.
         *
         *     The directory and the adapter options are validated here so that an obvious mistake
         *     is a 400 with a message, rather than a job that starts and immediately fails.
         */
        post: operations["start_scan_api_import_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a manifest back for review
         * @description Fetch a scan's proposal. The scan job's result carries the id.
         */
        get: operations["read_manifest_api_import_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit an accepted manifest into the catalog
         * @description Create or update the dataset this manifest describes.
         *
         *     Idempotent: committing the same manifest twice leaves the same rows. The manifest is
         *     stored verbatim, so what was accepted stays answerable later.
         */
        post: operations["commit_api_import_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-check a dataset's files against their hashes
         * @description Start a verify job. It reports drift and never repairs it.
         */
        post: operations["start_verify_api_import_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent jobs, newest first
         * @description List jobs, optionally narrowed to one kind or one status.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current state of one job, with a log tail
         * @description Snapshot a job. Take this before subscribing to its event stream.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a queued or running job
         * @description Request cancellation.
         *
         *     A queued job is cancelled outright. A running one is sent SIGTERM, and killed if it
         *     has not stopped within the grace period — cancellation that does not actually stop
         *     the work would be worse than none (ADR-0009).
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Splits of a dataset, with their composition
         * @description List splits. Composition is included so the picker can show it without a fan-out.
         */
        get: operations["list_splits_api_splits_get"];
        put?: never;
        /**
         * Create a sample-level split, seeded or imported
         * @description Draw a split, or adopt a published one, and store what reproduces it.
         *
         *     A seeded split is per sample, so no two views of one part can straddle the boundary;
         *     training gets normals only; and the draw is stratified by capture group so an
         *     acquisition-batch effect cannot land entirely on one side (ADR-0011).
         *
         *     The `imported` strategy instead reads the partition out of the manifest the dataset
         *     was committed from, because a benchmark's published number is only comparable against
         *     the benchmark's own partition.
         */
        post: operations["create_split_api_splits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/splits/{split_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One split
         * @description One split and its exact composition.
         */
        get: operations["get_split_api_splits__split_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdapterInfo
         * @description One registered adapter, with the schema its options form is generated from.
         */
        AdapterInfo: {
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Options Schema */
            options_schema: {
                [key: string]: unknown;
            };
        };
        /**
         * BulkLabelFilter
         * @description The browser's filters, as a request body rather than a query string.
         */
        BulkLabelFilter: {
            label?: components["schemas"]["Label"] | null;
            /** Channel Id */
            channel_id?: number | null;
            /** Split Id */
            split_id?: number | null;
            /** @description Only meaningful together with `split_id`. */
            subset?: components["schemas"]["Subset"] | null;
        };
        /**
         * BulkLabelRequest
         * @description Label a selection, or everything matching a filter.
         *
         *     The two ways of naming the target are deliberately exclusive. A selection is what the
         *     grid's checkboxes produce; a filter is what "label everything I am currently looking
         *     at" means, and it is evaluated *server-side* from the same clause the grid pages with,
         *     so it cannot label a different set than the one whose count was shown.
         */
        BulkLabelRequest: {
            label: components["schemas"]["Label"];
            /**
             * Sample Ids
             * @description An explicit selection. Ids outside this dataset are ignored.
             */
            sample_ids?: number[] | null;
            /** @description Every sample matching these filters. An empty object means the whole dataset. */
            filters?: components["schemas"]["BulkLabelFilter"] | null;
        };
        /** BulkLabelResult */
        BulkLabelResult: {
            /** Updated */
            updated: number;
        };
        /**
         * Channel
         * @description One entry of a dataset's acquisition-channel dictionary.
         */
        Channel: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /**
         * ChannelMapping
         * @description One source directory name and the canonical channel it was read as.
         *
         *     The whole table is editable before commit: the fuzzy matcher is a convenience, not
         *     an authority, and a dataset with unfamiliar channel names must be importable without
         *     a code change (ADR-0006).
         */
        ChannelMapping: {
            /** Source */
            source: string;
            /** Channel */
            channel: string;
            /** Matched By */
            matched_by: string;
        };
        /** CommitRequest */
        CommitRequest: {
            manifest: components["schemas"]["Manifest-Input"];
            /**
             * Dataset Id
             * @description Commit into this dataset explicitly. Omit to resolve by the manifest's root path, which is what makes re-importing a directory idempotent.
             */
            dataset_id?: number | null;
        };
        /** CommitResponse */
        CommitResponse: {
            /** Dataset Id */
            dataset_id: number;
            /** Dataset Created */
            dataset_created: boolean;
            /** Manifest Id */
            manifest_id: string;
            /** Samples Created */
            samples_created: number;
            /** Samples Updated */
            samples_updated: number;
            /** Images Created */
            images_created: number;
            /** Images Updated */
            images_updated: number;
            /** Channels */
            channels: number;
            /**
             * Masks
             * @description Images that now carry pixel-level ground truth.
             * @default 0
             */
            masks: number;
            /**
             * Missing Paths
             * @description Recorded images this manifest no longer mentions. Reported, not deleted.
             */
            missing_paths: string[];
        };
        /** CreateSplitRequest */
        CreateSplitRequest: {
            /** Dataset Id */
            dataset_id: number;
            /** Name */
            name: string;
            /**
             * Seed
             * @description Same seed and params reproduce this split.
             * @default 0
             */
            seed: number;
            params?: components["schemas"]["SplitParams-Input"];
        };
        /** DatasetDetail */
        DatasetDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Root Path */
            root_path: string;
            /** Adapter */
            adapter: string | null;
            /** Created At */
            created_at: string;
            /** Notes */
            notes: string | null;
            /** Samples */
            samples: number;
            /** Images */
            images: number;
            /** Label Counts */
            label_counts: {
                [key: string]: number;
            };
            /** Manifest Path */
            manifest_path: string | null;
            /** Channels */
            channels: components["schemas"]["Channel"][];
            /** Group Keys */
            group_keys: string[];
            /**
             * Splits
             * @default 0
             */
            splits: number;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Root Path */
            root_path: string;
            /** Adapter */
            adapter: string | null;
            /** Created At */
            created_at: string;
            /** Notes */
            notes: string | null;
            /** Samples */
            samples: number;
            /** Images */
            images: number;
            /** Label Counts */
            label_counts: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Schema Version */
            schema_version: number;
            /** Db Path */
            db_path: string;
            /** Data Dir */
            data_dir: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * ImageSummary
         * @description One image of a sample, as the grid and the viewer need it.
         *
         *     Carries no pixels: the client builds `/api/images/{id}/{tier}` URLs itself, so a page
         *     of thumbnails is that many cacheable image requests rather than one enormous JSON
         *     document.
         */
        ImageSummary: {
            /** Id */
            id: number;
            /** Channel */
            channel: string | null;
            /** Channel Id */
            channel_id: number | null;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Bit Depth */
            bit_depth: number;
            /** File Size */
            file_size: number;
            /** Path */
            path: string;
        };
        /**
         * ImageTier
         * @enum {string}
         */
        ImageTier: "thumb" | "preview" | "full";
        /**
         * JobDetail
         * @description A job plus everything needed to render its screen before the socket opens.
         */
        JobDetail: {
            /** Id */
            id: number;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Message */
            message: string | null;
            /** Experiment Id */
            experiment_id: number | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Log Tail */
            log_tail: string[];
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "import" | "verify" | "prewarm" | "train" | "infer";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JobSummary
         * @description A job as the list view sees it.
         */
        JobSummary: {
            /** Id */
            id: number;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Message */
            message: string | null;
            /** Experiment Id */
            experiment_id: number | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
        };
        /**
         * Label
         * @enum {string}
         */
        Label: "normal" | "defect" | "unlabeled";
        /**
         * LabelSource
         * @description Where a label came from, so hand corrections survive a re-import (ADR-0013).
         * @enum {string}
         */
        LabelSource: "import" | "manual";
        /** LabelUpdate */
        LabelUpdate: {
            label: components["schemas"]["Label"];
        };
        /**
         * Manifest
         * @description A complete import proposal. Nothing has been written when this is produced.
         */
        "Manifest-Input": {
            /**
             * Manifest Version
             * @default 1
             */
            manifest_version: number;
            /** Adapter */
            adapter: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Dataset Name */
            dataset_name: string;
            /** Root Path */
            root_path: string;
            /** Channels */
            channels?: string[];
            /** Channel Mapping */
            channel_mapping?: components["schemas"]["ChannelMapping"][];
            /** Samples */
            samples?: components["schemas"]["ManifestSample-Input"][];
            /** Warnings */
            warnings?: components["schemas"]["ManifestWarning-Input"][];
            stats?: components["schemas"]["ManifestStats-Input"];
            /** Scanned At */
            scanned_at?: string;
        };
        /**
         * Manifest
         * @description A complete import proposal. Nothing has been written when this is produced.
         */
        "Manifest-Output": {
            /**
             * Manifest Version
             * @default 1
             */
            manifest_version: number;
            /** Adapter */
            adapter: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Dataset Name */
            dataset_name: string;
            /** Root Path */
            root_path: string;
            /** Channels */
            channels: string[];
            /** Channel Mapping */
            channel_mapping: components["schemas"]["ChannelMapping"][];
            /** Samples */
            samples: components["schemas"]["ManifestSample-Output"][];
            /** Warnings */
            warnings: components["schemas"]["ManifestWarning-Output"][];
            stats: components["schemas"]["ManifestStats-Output"];
            /** Scanned At */
            scanned_at: string;
        };
        /** ManifestImage */
        "ManifestImage-Input": {
            /** Path */
            path: string;
            /** Channel */
            channel?: string | null;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Bit Depth */
            bit_depth: number;
            /** File Size */
            file_size: number;
            /**
             * Mask Path
             * @description Pixel-level ground truth for this image, referenced in place like the image. `null` for the datasets that have none, which is most of them.
             */
            mask_path?: string | null;
        };
        /** ManifestImage */
        "ManifestImage-Output": {
            /** Path */
            path: string;
            /** Channel */
            channel: string | null;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Bit Depth */
            bit_depth: number;
            /** File Size */
            file_size: number;
            /**
             * Mask Path
             * @description Pixel-level ground truth for this image, referenced in place like the image. `null` for the datasets that have none, which is most of them.
             */
            mask_path: string | null;
        };
        /** ManifestSample */
        "ManifestSample-Input": {
            /** Group Key */
            group_key: string;
            /** External Id */
            external_id: string;
            /** @default unlabeled */
            label: components["schemas"]["Label"];
            /** @description The subset this sample belongs to according to the source dataset. Only adapters that read a published split fill this in; it is what a split with the `imported` strategy is built from, so that a benchmark can be run under the same partition the published numbers used. */
            subset?: components["schemas"]["Subset"] | null;
            /**
             * Notes
             * @description Free text the adapter read from the source, such as a defect type. Carried onto the sample so a breakdown by defect type is possible without a schema that enumerates defect types.
             */
            notes?: string | null;
            /** Images */
            images?: components["schemas"]["ManifestImage-Input"][];
        };
        /** ManifestSample */
        "ManifestSample-Output": {
            /** Group Key */
            group_key: string;
            /** External Id */
            external_id: string;
            /** @default unlabeled */
            label: components["schemas"]["Label"];
            /** @description The subset this sample belongs to according to the source dataset. Only adapters that read a published split fill this in; it is what a split with the `imported` strategy is built from, so that a benchmark can be run under the same partition the published numbers used. */
            subset: components["schemas"]["Subset"] | null;
            /**
             * Notes
             * @description Free text the adapter read from the source, such as a defect type. Carried onto the sample so a breakdown by defect type is possible without a schema that enumerates defect types.
             */
            notes: string | null;
            /** Images */
            images: components["schemas"]["ManifestImage-Output"][];
        };
        /**
         * ManifestStats
         * @description What the scan actually did, so the review screen can show its scope.
         */
        "ManifestStats-Input": {
            /**
             * Files Seen
             * @default 0
             */
            files_seen: number;
            /**
             * Files Excluded
             * @default 0
             */
            files_excluded: number;
            /**
             * Files Skipped
             * @default 0
             */
            files_skipped: number;
            /**
             * Samples
             * @default 0
             */
            samples: number;
            /**
             * Images
             * @default 0
             */
            images: number;
            /**
             * Masks
             * @default 0
             */
            masks: number;
        };
        /**
         * ManifestStats
         * @description What the scan actually did, so the review screen can show its scope.
         */
        "ManifestStats-Output": {
            /**
             * Files Seen
             * @default 0
             */
            files_seen: number;
            /**
             * Files Excluded
             * @default 0
             */
            files_excluded: number;
            /**
             * Files Skipped
             * @default 0
             */
            files_skipped: number;
            /**
             * Samples
             * @default 0
             */
            samples: number;
            /**
             * Images
             * @default 0
             */
            images: number;
            /**
             * Masks
             * @default 0
             */
            masks: number;
        };
        /** ManifestWarning */
        "ManifestWarning-Input": {
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
            /** Paths */
            paths?: string[];
        };
        /** ManifestWarning */
        "ManifestWarning-Output": {
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
            /** Paths */
            paths: string[];
        };
        /** PrewarmRequest */
        PrewarmRequest: {
            /** Dataset Id */
            dataset_id: number;
            /**
             * Tiers
             * @description Which tiers to render. Defaults to every cacheable tier.
             */
            tiers?: components["schemas"]["ImageTier"][] | null;
        };
        /** SamplePage */
        SamplePage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["SampleSummary"][];
        };
        /** SampleSummary */
        SampleSummary: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Group Key */
            group_key: string;
            /** External Id */
            external_id: string;
            label: components["schemas"]["Label"];
            label_source: components["schemas"]["LabelSource"];
            /** Notes */
            notes: string | null;
            /** Images */
            images: components["schemas"]["ImageSummary"][];
        };
        /** ScanRequest */
        ScanRequest: {
            /** Root Path */
            root_path: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Adapter
             * @default channel_folders
             */
            adapter: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** SplitDetail */
        SplitDetail: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /** Seed */
            seed: number;
            /** Created At */
            created_at: string;
            /** Composition */
            composition: components["schemas"]["SubsetComposition"][];
            params: components["schemas"]["SplitParams-Output"];
        };
        /**
         * SplitParams
         * @description How a split is drawn. Stored with the split so it can be rebuilt exactly.
         */
        "SplitParams-Input": {
            /** @default normal_only_train */
            strategy: components["schemas"]["SplitStrategy"];
            /**
             * Train Normal Fraction
             * @description Share of normal samples used for fitting. Defects never train.
             * @default 0.6
             */
            train_normal_fraction: number;
            /**
             * Val Normal Fraction
             * @description Share of normal samples held out for threshold selection.
             * @default 0.2
             */
            val_normal_fraction: number;
            /**
             * Val Defect Fraction
             * @description Share of defect samples in validation; the rest are reported on.
             * @default 0.3
             */
            val_defect_fraction: number;
            /**
             * @description Where unlabelled samples go. They are excluded from every metric but must be scored to appear in the ranked lists. `null` leaves them out of the split.
             * @default test
             */
            unlabeled_subset: components["schemas"]["Subset"] | null;
            /**
             * Manifest Id
             * @description Which import proposal an `imported` split was materialized from. Recorded so the partition stays traceable to the file that asserted it; ignored by every other strategy.
             */
            manifest_id?: string | null;
        };
        /**
         * SplitParams
         * @description How a split is drawn. Stored with the split so it can be rebuilt exactly.
         */
        "SplitParams-Output": {
            /** @default normal_only_train */
            strategy: components["schemas"]["SplitStrategy"];
            /**
             * Train Normal Fraction
             * @description Share of normal samples used for fitting. Defects never train.
             * @default 0.6
             */
            train_normal_fraction: number;
            /**
             * Val Normal Fraction
             * @description Share of normal samples held out for threshold selection.
             * @default 0.2
             */
            val_normal_fraction: number;
            /**
             * Val Defect Fraction
             * @description Share of defect samples in validation; the rest are reported on.
             * @default 0.3
             */
            val_defect_fraction: number;
            /**
             * @description Where unlabelled samples go. They are excluded from every metric but must be scored to appear in the ranked lists. `null` leaves them out of the split.
             * @default test
             */
            unlabeled_subset: components["schemas"]["Subset"] | null;
            /**
             * Manifest Id
             * @description Which import proposal an `imported` split was materialized from. Recorded so the partition stays traceable to the file that asserted it; ignored by every other strategy.
             */
            manifest_id: string | null;
        };
        /**
         * SplitStrategy
         * @enum {string}
         */
        SplitStrategy: "normal_only_train" | "imported";
        /**
         * Subset
         * @enum {string}
         */
        Subset: "train" | "val" | "test";
        /**
         * SubsetComposition
         * @description What a subset actually contains, so a split can report itself honestly.
         */
        SubsetComposition: {
            subset: components["schemas"]["Subset"];
            /** Total */
            total: number;
            /** Normal */
            normal: number;
            /** Defect */
            defect: number;
            /** Unlabeled */
            unlabeled: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Dataset Id */
            dataset_id: number;
        };
        /**
         * WarningCode
         * @description Why the operator is being asked to look at something.
         * @enum {string}
         */
        WarningCode: "variable_channel_count" | "unassigned_channel" | "unknown_channel_name" | "duplicate_hash" | "unreadable_file" | "empty_file" | "ambiguous_sample_id" | "unmatched_path" | "conflicting_directories" | "missing_mask";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    get_dataset_api_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_datasets__dataset_id__samples_get: {
        parameters: {
            query?: {
                label?: components["schemas"]["Label"] | null;
                /** @description Samples that have an image in this channel. */
                channel_id?: number | null;
                split_id?: number | null;
                /** @description Only meaningful together with `split_id`. */
                subset?: components["schemas"]["Subset"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_labels_api_datasets__dataset_id__samples_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkLabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkLabelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_api_datasets__dataset_id__samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_label_api_datasets__dataset_id__samples__sample_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_prewarm_api_images_prewarm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrewarmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tier_api_images__image_id___tier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
                tier: components["schemas"]["ImageTier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": unknown;
                    "image/png": unknown;
                };
            };
            /** @description The client's copy is current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_adapters_api_import_adapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterInfo"][];
                };
            };
        };
    };
    start_scan_api_import_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_manifest_api_import_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_import_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_verify_api_import_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["JobKind"] | null;
                status?: components["schemas"]["JobStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_splits_api_splits_get: {
        parameters: {
            query: {
                /** @description Dataset to list splits for. */
                dataset_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_split_api_splits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_split_api_splits__split_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
