#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate mdBook capability and benchmark pages from checked source data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BACKEND_SRC = ROOT / "backend" / "src"
DATA_PATH = ROOT / "docs" / "benchmarks" / "results.json"
OUTPUT = ROOT / "docs" / "book" / "generated"


def _methods(data: dict[str, Any]) -> str:
    sys.path.insert(0, str(BACKEND_SRC))
    try:
        from anomaly_lab.models.registry import describe_all

        descriptions = describe_all()
    finally:
        sys.path.pop(0)

    rows = []
    details = []
    curated = data["methods"]
    for item in descriptions:
        meta = curated[item.key]
        capabilities = item.capabilities
        portable = ", ".join(value.value for value in capabilities.portable_formats) or "—"
        rows.append(
            f"| `{item.key}` | {item.title} | {meta['family']} | {meta['maturity']} | "
            f"{'yes' if capabilities.supports_resume else 'no'} | {portable} |"
        )
        details.append(
            f"## {item.title}\n\n`{item.key}` · **{meta['family']}** · "
            f"{meta['maturity']}\n\n{item.summary}\n\n"
            f"- Preferred device: `{capabilities.preferred_device.value}`\n"
            f"- Requires fitting: {'yes' if capabilities.requires_training else 'no'}\n"
            f"- Anomaly map: {'yes' if capabilities.produces_anomaly_map else 'no'}\n"
            f"- Diagnostics: {'yes' if capabilities.produces_diagnostics else 'no'}\n"
            f"- Exact continuation: {'yes' if capabilities.supports_resume else 'no'}\n"
            f"- Dataset-specific: {'yes' if capabilities.dataset_specific else 'no'}\n"
            f"- Portable formats: {portable}\n"
        )
    unknown = sorted(set(curated) - {item.key for item in descriptions})
    if unknown:
        raise ValueError(f"benchmark metadata has unregistered methods: {', '.join(unknown)}")
    return "\n".join(
        [
            "<!-- Generated by scripts/build-book.py; do not edit. -->",
            "# Supported methods",
            "",
            "This page is generated from the live model registry and checked method metadata. "
            "Availability on one machine still depends on optional packages and local assets; the app "
            "reports that separately.",
            "",
            "| Key | Method | Family | Maturity | Resume | ONNX/export |",
            "|---|---|---|---|---:|---|",
            *rows,
            "",
            "**Maturity is an evidence decision, not an upstream popularity label.** Experimental methods "
            "remain usable for research but have not cleared this workbench's public promotion gate.",
            "",
            *details,
            "## Adding another method",
            "",
            "Follow [Add a model](../add-model.md). One plugin module and one registry entry should be "
            "sufficient; rerun `scripts/build-book.py` afterwards.",
            "",
        ]
    )


def _quality_svg(protocol: dict[str, Any]) -> str:
    rows = protocol["rows"]
    metrics = [
        ("image_roc_auc", "Image ROC-AUC"),
        ("pixel_roc_auc", "Pixel ROC-AUC"),
        ("au_pro", "AU-PRO"),
    ]
    width, left, top, row_h = 920, 175, 58, 30
    height = top + len(rows) * len(metrics) * row_h + 54
    colors = {rows[0]["method"]: "#0f8fa8", rows[1]["method"]: "#8b6bb7"}
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        "<style>text{font-family:system-ui,sans-serif;fill:#20252b}.small{font-size:12px}.label{font-size:13px;font-weight:600}.title{font-size:18px;font-weight:700}</style>",
        f'<text x="16" y="28" class="title">{protocol["title"]}</text>',
        '<line x1="175" y1="42" x2="875" y2="42" stroke="#d8dde3"/>',
    ]
    y = top
    for row in rows:
        for key, label in metrics:
            value = row[key]
            descriptor = f"{row['class']} · {row['method']} · {label}"
            bar = 680 * value
            parts.extend(
                [
                    f'<text x="16" y="{y + 16}" class="small">{descriptor}</text>',
                    f'<rect x="{left}" y="{y}" width="680" height="20" rx="3" fill="#edf0f3"/>',
                    f'<rect x="{left}" y="{y}" width="{bar:.1f}" height="20" rx="3" fill="{colors[row["method"]]}"/>',
                    f'<text x="{left + bar + 7:.1f}" y="{y + 15}" class="label">{value:.4f}</text>',
                ]
            )
            y += row_h
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def _resource_svg(rows: list[dict[str, Any]]) -> str:
    width, height, left, top, row_h = 920, 340, 210, 48, 38
    maximum = max(row["inference_ms"] for row in rows)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        "<style>text{font-family:system-ui,sans-serif;fill:#20252b}.small{font-size:13px}.value{font-size:13px;font-weight:600}.title{font-size:18px;font-weight:700}</style>",
        '<text x="16" y="27" class="title">Measured MPS inference latency</text>',
    ]
    colors = {"Dinomaly": "#0f8fa8", "GLASS": "#8b6bb7", "AnomalyVFM": "#d17a22"}
    for index, row in enumerate(rows):
        y = top + index * row_h
        bar = 620 * row["inference_ms"] / maximum
        label = f"{row['method']} · {row['prepared']}x{row['prepared']}"
        parts.extend(
            [
                f'<text x="16" y="{y + 18}" class="small">{label}</text>',
                f'<rect x="{left}" y="{y}" width="620" height="24" rx="3" fill="#edf0f3"/>',
                f'<rect x="{left}" y="{y}" width="{bar:.1f}" height="24" rx="3" fill="{colors[row["method"]]}"/>',
                f'<text x="{left + bar + 8:.1f}" y="{y + 18}" class="value">{row["inference_ms"]:.1f} ms</text>',
            ]
        )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def _benchmarks(data: dict[str, Any]) -> tuple[str, dict[str, str]]:
    blocks = [
        "<!-- Generated by scripts/build-book.py; do not edit. -->",
        "# Public benchmarks",
        "",
        "These are checked measurements from the repository's public-data gates, not upstream leaderboard "
        "numbers. Compare rows **within one protocol block only**: prepared sizes and PatchCore settings "
        "differ between gates. Each block links to the full protocol, assets, versions, decision rule, and "
        "limitations.",
        "",
    ]
    svgs: dict[str, str] = {}
    for protocol in data["quality_protocols"]:
        svg_name = f"{protocol['id']}.svg"
        svgs[svg_name] = _quality_svg(protocol)
        blocks.extend(
            [
                f"## {protocol['title']}",
                "",
                f"**Protocol:** {protocol['dataset']}; {protocol['prepared']}; seed "
                f"`{protocol['seed']}`. {protocol['note']} [Full evidence]({protocol['source']}).",
                "",
                f"![{protocol['title']}]({svg_name})",
                "",
                "| Class | Method | Image ROC-AUC | Pixel ROC-AUC | AU-PRO | Train | Infer | Peak RSS |",
                "|---|---|---:|---:|---:|---:|---:|---:|",
            ]
        )
        for row in protocol["rows"]:
            blocks.append(
                f"| {row['class']} | {row['method']} | {row['image_roc_auc']:.4f} | "
                f"{row['pixel_roc_auc']:.4f} | {row['au_pro']:.4f} | {row['train_s']:.1f} s | "
                f"{row['infer_s']:.1f} s | {row['peak_rss_gib']:.2f} GiB |"
            )
        blocks.append("")

    resource_rows = data["resource_rows"]
    svgs["mps-inference.svg"] = _resource_svg(resource_rows)
    blocks.extend(
        [
            "## Resource measurements",
            "",
            "![MPS inference latency by method and prepared size](mps-inference.svg)",
            "",
            "Prepared size changes the workload, so these bars describe Mac feasibility and scaling—not "
            "a speed race between methods. Values are batch-one warm inference from the linked smoke gates.",
            "",
            "| Method | Device | Prepared | Inference | Peak RSS | MPS driver | Evidence |",
            "|---|---|---:|---:|---:|---:|---|",
        ]
    )
    for row in resource_rows:
        blocks.append(
            f"| {row['method']} | {row['device']} | {row['prepared']}² | "
            f"{row['inference_ms']:.1f} ms | {row['peak_rss_gib']:.2f} GiB | "
            f"{row['driver_gib']:.2f} GiB | [log]({row['source']}) |"
        )
    blocks.extend(
        [
            "",
            "## What the evidence supports",
            "",
            "- Dinomaly cleared its predeclared two-class quality floors and is the transformer "
            "reconstruction reference, at a substantially longer fit than PatchCore.",
            "- GLASS remained experimental: it cleared pixel floors but missed the image ROC-AUC floor "
            "by 0.0062 under its bounded gate.",
            "- AnomalyVFM passed the local resource gate but is not yet an integrated method; quality and "
            "offline asset handling remain unproven in this workbench.",
            "- These two VisA classes are promotion gates, not a claim of universal performance. New data "
            "needs its own split, masks, baselines, and failure review.",
            "",
        ]
    )
    return "\n".join(blocks), svgs


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"stale generated book file: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail instead of updating stale output"
    )
    args = parser.parse_args()
    data: dict[str, Any] = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("unsupported benchmark-data schema")
    benchmarks, svgs = _benchmarks(data)
    outputs = {
        OUTPUT / "methods.md": _methods(data),
        OUTPUT / "benchmarks.md": benchmarks,
        **{OUTPUT / name: content for name, content in svgs.items()},
    }
    return (
        0
        if all(_write_or_check(path, content, args.check) for path, content in outputs.items())
        else 1
    )


if __name__ == "__main__":
    raise SystemExit(main())
